name: Deploy Vue App

on:
  push:
    branches:
      - main # 触发条件，监视 main 分支的推送

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v20.13.1' # 设置 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*" # Vue 项目的构建输出目录
          target: ${{ secrets.REMOTE_PATH }} # 远程服务器路径